server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8085/eureka/


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  application.name: service-resources
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://service-authorization:8099
          jwk-set-uri: http://service-authorization:8099/oauth2/jwks

        
        opaque:
          introspection-uri: "http://service-authorization:8099/connect/introspect"
          introspection-client-id: client-test
          introspection-client-secret: password
